-- Bookings
create table
  public.bookings (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    startDate timestamp without time zone null,
    endDate timestamp without time zone null,
    numNights smallint null,
    numGuests smallint null,
    cabinPrice real null,
    extrasPrice real null,
    totalPrice real null,
    status text null,
    hasBreakfast boolean null,
    isPaid boolean null,
    observations text null,
    cabinId bigint null,
    guestId bigint null,
    constraint bookings_pkey primary key (id),
    constraint bookings_cabinId_fkey foreign key ("cabinId") references cabins (id),
    constraint bookings_guestId_fkey foreign key ("guestId") references guests (id)
  ) tablespace pg_default;

-- Cabins
create table
  public.cabins (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    maxCapacity smallint null,
    regularPrice smallint null,
    discount smallint null,
    description text null,
    image text null,
    constraint cabins_pkey primary key (id)
  ) tablespace pg_default;

-- Guests
create table
  public.guests (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    fullName text null,
    email text null,
    nationalID text null,
    nationality text null,
    countryFlag text null,
    constraint guests_pkey primary key (id)
  ) tablespace pg_default;

-- create table
create table
  public.settings (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    minBookingLength smallint null,
    maxBookingLength smallint null,
    maxGuestsPerBooking smallint null,
    breakfastPrice real null,
    constraint settings_pkey primary key (id)
  ) tablespace pg_default;

-- Create avatars bucket.
insert into storage.buckets
  (id, name)
values
  ('avatars', 'avatars');

-- Create avatars bucket.
insert into storage.buckets
  (id, name)
values
  ('cabin-images', 'cabin-images');
